name: Deploy to shinyapps.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Print environment variables
      run: |
        echo "SHINYAPPS_ACCOUNT=${{ secrets.SHINYAPPS_ACCOUNT }}"
        echo "SHINYAPPS_TOKEN=${{ secrets.SHINYAPPS_TOKEN }}"
        echo "SHINYAPPS_SECRET=${{ secrets.SHINYAPPS_SECRET }}"

    - name: Deploy to shinyapps.io
      env:
        SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
        SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
        SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}

      run: |
        pip install rsconnect-python
        rsconnect deploy shiny --account ${{ secrets.SHINYAPPS_ACCOUNT }} --token ${{ secrets.SHINYAPPS_TOKEN }} --secret ${{ secrets.SHINYAPPS_SECRET }} --appDir .